name: mc_status
description: A simple command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0

dependencies: 
  args: ^2.3.0
  collection: ^1.15.0
  dart_minecraft:
    git: https://github.com/TheKingDave/dart_minecraft.git
  dotenv: ^3.0.0
  shelf: ^1.2.0
  shelf_router: ^1.1.2
  shelf_static: ^1.1.0
  shelf_web_socket: ^1.0.1
